<a href="https://colab.research.google.com/github/xDaryamo/BreastCancerPrediction/blob/master/breast_cancer_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import delle dipendenze

In [ ]:
import pandas as pd
import os

# Ottenimento del dataset

In [ ]:

root="https://raw.githubusercontent.com/xDaryamo/BreastCancerPrediction/master/dataset.csv"

#Caricamento del csv dalla repo GitHub
df = pd.read_csv(root)

df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]